### PR TITLE
Fix for some compilers

### PR DESCRIPTION
**Pull request by TheElementalOfCreation**
Added a fix for some compilers that would cause an error from z80.c containing a string that was too long by splitting it into multiple strings that get concatenated

### CODE REVIEW

**Comment by pixelherodev** [comment]
I have no objections to merging this.

**Comment by pixelherodev** [comment]
I would, however, prefer if the .sh file was removed entirely.

A better solution would be to use Python to take the one big file and split it into 64 KB chunks.

**Comment by ddevault** [comment]
>A better solution would be to use Python

Let's not become *less* portable.

**Comment by pixelherodev** [comment]
Is there any reason not to just have a copy of the table as a .c stored in the repo instead of regenerating it at compile time?

**Comment by ddevault** [comment]
Yes, don't check in generated code. There should only be one authoritative source of truth, which is the .tab files.

**Comment by pixelherodev** [comment]
Maybe instead of splitting the file into pieces, the embedded version should be generated differently? I think e.g. `xxd -i` should be able to produce a character array, and writing a simple tool for it is rather trivial

**Comment by earboxer** [comment]
"some compilers" include gcc 7 (default `gcc` ubuntu 18.04) The `gcc-8` package can be installed to remedy this.

**Pull request closed without merging**
